/**
 * Bakes two woff2 files into a committed TypeScript module.
 *
 * A `font-family: Inter, sans-serif` declaration renders differently on
 * macOS and in a container — different metrics, different wrapping, broken
 * cards. Reading the fonts from node_modules at runtime would work until
 * someone prunes dev dependencies, so the bytes are committed instead.
 *
 * Run: pnpm run embed-fonts
 */
import { createRequire } from 'node:module'
import { mkdir, readFile, writeFile } from 'node:fs/promises'

const require = createRequire(import.meta.url)

/**
 * Resolved through the package rather than by path. pnpm's store layout puts
 * these under a hashed directory, so a hardcoded node_modules path breaks on
 * the next install.
 */
const FILES = {
  inter: '@fontsource/inter/files/inter-latin-600-normal.woff2',
  mono: '@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2',
}

const parts = []
for (const [name, specifier] of Object.entries(FILES)) {
  const base64 = (await readFile(require.resolve(specifier))).toString('base64')
  parts.push(`export const ${name}Woff2 =\n  '${base64}'`)
}

// On a fresh checkout the module is regenerated before src/image exists.
await mkdir('src/image', { recursive: true })
await writeFile(
  'src/image/fonts.ts',
  `/* Generated by scripts/embed-fonts.mjs. Do not edit. */\n\n${parts.join('\n\n')}\n`,
)
console.log('Wrote src/image/fonts.ts')
